workflows:
  react-native-android:
    name: build-taptitan
    instance_type: mac_mini_m2
    scripts:
      - name: Install and Build
        script: |
          # Go to where your package.json is
          cd template
          
          # Install the missing parts (node_modules)
          npm install
          
          # Now go build the APK
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - "**/build/outputs/apk/debug/*.apk"
      
scripts:
  - |
    cd template && npm install
    cd template/android && chmod +x gradlew && ./gradlew assembleDebug
    
